name: nusantara_test_flutter_developer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  get: 4.6.6
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/navigation/

flutter_gen:
  output: app/lib/core/assets/
